image: chialab/php-dev:7.3

stages:
  - build
  - test
  - report

build:
  stage: build
  script:
    - composer install
  artifacts:
    paths:
      - vendor
    expire_in: 30 min

test:code-quality:
  stage: test
  script:
    - vendor/bin/phpqa
  dependencies:
    - build

test:unit:
  stage: test
  script:
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
  dependencies:
    - build

pages:
  stage: report
  script:
    - echo "To be implemented"
